name: C Workflow
'on':
  push:
    branches:
    - project-run/C
  pull_request:
    branches:
    - project-run/C
jobs:
  test:
    name: Test C
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: C
    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y libsqlite3-dev libssl-dev
    - name: Install Kore
      run: wget -qO - https://kore.io/install | sudo bash
    - name: Build
      working-directory: C
      run: make
    - name: Test
      working-directory: C
      run: make test
