name: C Workflow
'on':
  push:
    branches:
    - project-run/C
  pull_request:
    branches:
    - project-run/C
jobs:
  test:
    name: Test C
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: C
    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git libsqlite3-dev libssl-dev
    - name: Install Kore
      run: |
        git clone https://github.com/jorisvink/kore.git /tmp/kore
        cd /tmp/kore
        make
        sudo make install
    - name: Build
      working-directory: C
      run: make
    - name: Test
      working-directory: C
      run: make test
