name: CKore Workflow
'on':
  push:
    branches:
    - project-run/CKore
  pull_request:
    branches:
    - project-run/CKore
jobs:
  test:
    name: Test CKore
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: CKore
    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y libsqlite3-dev libssl-dev
    - name: Install Kore
      run: wget -qO - https://kore.io/install | bash
    - name: Build
      working-directory: CKore
      run: make
    - name: Test
      working-directory: CKore
      run: make test
