name: Swift Workflow
'on':
  push:
    branches:
    - project-run/Swift
  pull_request:
    branches:
    - project-run/Swift
jobs:
  test:
    name: Test Swift
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Swift
    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: swift test
